#!/usr/bin/perl
use strict;
use warnings;
use POE qw(Component::IRC::State);
use Data::Dumper;

my $nickname  = 'Blah' . $$;
my $ircserver = 'irc.redbrick.dcu.ie';
my $channel   = '#moses';

my $irc = POE::Component::IRC::State->spawn(
    nick         => $nickname,
    server       => $ircserver,
    debug        => 1,
    plugin_debug => 1,
    options      => { trace => 0 },
) or die "Oh noooo! $!";

POE::Session->create(
    package_states => [
        'main' => [ qw(_start irc_001 irc_chan_mode) ],
    ],
);

$poe_kernel->run();
exit 0;

sub _start {
# Create and load our plugin
    $irc->yield( register => 'all' );
    $irc->yield( connect => {} );
    undef;
}

sub irc_001 {
    $irc->yield( join => $channel );
    undef;
}

sub irc_chan_mode {
    my ( $channel, $mode, $mask ) = @_[ ARG1..ARG3 ];
    warn Data::Dumper->Dumper( $irc->channel_ban_list($channel));
    undef;
}
__END__
